print(" ------------------------------------------------------")
print("                     * Calculator *                   ")
print(" ------------------------------------------------------")
print("\n")
print("            Your Options are       \n")
print(" 1.Addition \n 2.Subtraction \n 3.Multiplication \n 4.Division \n 5.Power \n 6.floor division \n 7.Remainder \n")
print(" ------------------------------------------------------")
option=int(input("      Enter your option :"))
print(" ------------------------------------------------------")
print("\n")
if option==1:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("--------------------")
   print(" Addtion is :",a+b)
   print("--------------------")
elif option==2:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("-----------------------")
   print(" Suntraction is :",a-b)
   print("-----------------------")
elif option==3:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("---------------------------")
   print(" Multiplication is :",a*b)
   print("---------------------------")
elif option==4:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("-----------------------")
   print("  Division is :",a/b)
   print("-----------------------")
elif option==5:
   a=int(input("Enter base number:"))
   b=int(input("Enter power number:"))
   print("-------------------")
   print("  Power is :",a**b)
   print("-------------------")
elif option==6:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("-----------------------------")
   print("  Floor division is :",a//b)
   print("-----------------------------")
elif option==7:
   a=float(input("Enter first number:"))
   b=float(input("Enter second number:"))
   print("------------------------")
   print("  Remainder is :",a%b)
   print("------------------------")
else:
   print("-----------------")
   print(" Invalid Option")
   print("-----------------")
