print("\n\n")
name=str(input("Enter student name :"))
print("\n           Enter marks out of 100"          )
print("\n")
a=int(input("English   = "))
b=int(input("Maths     = "))
c=int(input("Physics   = "))
d=int(input("Chemistry = "))
e=int(input("IT        = "))
f=int(input("Geography = "))
t=a+b+c+d+e+f
p=t/6
print("\n\n")
print(" =============================================")
print("                 Report Card        ")
print(" =============================================")
print("   Name :",name)
print(" =============================================")
print(" | Subject     |Marks obtained| Marks out of|")
print(" ---------------------------------------------")
print(" | English     | "  ,a,"         |    100      |")
print(" | Maths       | "  ,b,"         |    100      |")
print(" | Physics     | "  ,c,"         |    100      |")
print(" | Chemistry   | "  ,d,"         |    100      |")
print(" | IT          | "  ,e,"         |    100      |")
print(" | Geography   | "  ,f,"         |    100      |")
print(" ----------------------------------------------")
print(" |   Total marks : ",t," /600")
print(" |   percentage :  ",p,"%")
print(" ===============================================")
